"""Generates SQLite Tables for interim data storage

This script populates the ./data/interim folders with files generated by sqlite.
"""
import sys
import sqlite3
from sqlite3 import Error
import helper_functions as helper
import table_definitions as definitions

_DATABASE_DIRECTORY = 'data/intermediate/'
_DATABASE_NAME = _DATABASE_DIRECTORY + 'happy-cows.db'

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as err:
        print(err)
    return None

def main():
    """Creates Database Tables"""
    helper.ensure_directory_exists(_DATABASE_DIRECTORY)
    conn = create_connection(_DATABASE_NAME)
    cursor = conn.cursor()
    try:
        cursor.execute(definitions.CREATE_CLASSIFICATION_TABLE)
        cursor.execute(definitions.CREATE_WEATHER_TABLE)
        cursor.execute(definitions.CREATE_PRODUCTION_VOLUME_TABLE)
    except Error as err:
        print(err)
    else:
        cursor.close()
        conn.close()
    return

if __name__ == "__main__":
    sys.exit(main())