"""Generates SQLite Tables for interim data storage

This script populates the ./data/interim folders with files generated by sqlite.
"""
import sys
import helper_functions as helper
import table_definitions as definitions

def main():
    """Creates Database Tables"""
    with helper.get_db_engine().connect() as connection:
        connection.execute(definitions.CREATE_CLASSIFICATION_TABLE)
        connection.execute(definitions.CREATE_WEATHER_TABLE)
        connection.execute(definitions.CREATE_PRODUCTION_VOLUME_TABLE)
    return

if __name__ == "__main__":
    sys.exit(main())